### PR TITLE
Add a bunch, general fixes

### PR DESCRIPTION
**Pull request by arubdesu**
Changed identifier to reflect home w/ @macvfx, added code signature verification, added some descriptions for munki, made sure all downloaded and almost all imported to munki, added .DS_STORE to gitignore, structured in folders.
Only X27 is still having issues due to unicode char in app name. Fixing that and adding pkg and installer recipes are left as outstanding tasks...

### CODE REVIEW

**Comment by macvfx** [comment]
Thanks Allister. 

I don’t see the unicode character in the app name. It’s full name is: "Xto7 for Final Cut Pro”. 

http://assistedediting.intelligentassistance.com/Xto7/

If there’s no easy way to get around the unicode character, then perhaps we can proceed with adding the other recipes into AutoPkg (removing Xto7 aka X27 if we have to).

Thanks for all your help.

:)

Mat X

**Comment by arubdesu** [comment]
`Project X\u20827.app` was what I was referring to, but turns out I just had a bad path in the munki recipe. All better.

**Comment by macvfx** [comment]
Thanks again Allister. Does that mean that the recipes are good to go now? What can I do?

:)

Mat X

**Comment by arubdesu** [comment]
Um, give 'em a spin! 😜 You can download a zip of [my fork](https://github.com/arubdesu/AutoPkg-1), and run autopkg in the unpacked directory or with the full path to each of the munki recipes from scratch(since they inherit the downloads). I have a testing repo setup on my laptop for iterating on stuff like this, or you can just redirect the pref temporarily to a tmp folder.

**Comment by macvfx** [comment]
I’ve tested all these recipes and they work (thank Allister for cleaning them up).

Can we add them to autopkg recipes as matx-recipes?

Please and thanks.

:)

Mat X

**Pull request merged**
